queries:
    user:
        list:
            query: |
                SELECT * FROM users [WHERE id = <id:int>]
        insert:
            query: |
                INSERT INTO users (name, lastname, birthday) VALUES (<name:str>, <lastname:str>, <birthday:str>)
        login:
            query: |
                SELECT * FROM users [WHERE id = <login:str>]
    company:
        list:
            query: |
                SELECT * FROM company WHERE id = <id:int> id1:[AND id1 = <id1:int>]
        insert:
            query: |
                INSERT INTO company (name) VALUES (<name:str>)
    in_array: |
        SELECT * FROM teste [WHERE ids IN <ids:in_array>]